### ISSUE TITLE
Slave server is useless for orderly consumer

### ISSUE THREAD

**Issue by xiukongtiao** [alibaba/RocketMQ#399] opened 2016-11-04 08:50 UTC
RocketMQ version: 3.5.8
Cluster: 1 master + 1 slave

**Case 1**
1. Produce 100 messages 
2. Kill master
3. Start up consumer( Not orderly ),  consumer read 100 messages from slave perfectly.

**Case 2**
1. Produce 100 messages 
2. Kill master
3. Start up orderly consumer,  consumer can not get any messages from slave.

The result of case 2 make me feel the slave is useless for orderly consumer, right?

Is it a bug,  or not?
Is there any backup solution to make the slave is useful for **orderly consumer**?

Thank you !

**Comment by gaoyf** [comment] 2016-11-04 09:52
1 Not a bug.
2 No, because the orderly consumers need distributed lock for locking the master.
You can read [this](http://blog.csdn.net/a417930422/article/details/52585495) for the concept of orderly message.

**Comment by xiukongtiao** [comment] 2016-11-04 09:57
Okay, Is there any backup solution to help the broker with high availability?
It looks like if we only have orderly consumer,  the slave is needless for us, am I correct?

**Comment by gaoyf** [comment] 2016-11-04 10:21
Your first question:
1 Create a common topic(not ordered topic).
2 Use `DefaultMQProducer.send(Message msg, MessageQueueSelector selector, Object arg)`  to send the ordered mesages to a stationary queue
3 Use `orderly consumer` to consume.
When broker is crash or restarting, the producer will send the messages to the other queue, thus bring the transient out-of-order, but when broker has started or crashed for ever, the message will become ordered.
So it is only *transient*.

Your second question:
May be yes, if you not care the data in the master is loss when master encounter some disaster.

**Comment by xiukongtiao** [comment] 2016-11-04 12:36
Thanks a lot!
But I still want to know why not allow orderly consumer get messages from slave when the master is crash.

What  the difficult point of slave switch master automatic is?

**Comment by zhouwei198732** [comment] 2016-11-10 17:52
yeah，this is a great problem, At present the program that we have adopted is mainly due to worry about message will be out of sequence when the master is crash and get message from slave , there are some limitations about standby replication, such as how to controll the message orderly when the master recovery and how to keep message orderly when the main standby node switch Automatically , there are still some problems need to deal with, but now In our current soluation, we try to keep the process simple, reliable and easy to be controlled. In furture version, we will take time to get rid of it, if you have some suggestions,  welcome to join us, generous with your criticism

**Comment by vongosling** [comment] 2016-12-27 14:48
i close this issue  if you have any question, please ask stackoverflow. http://stackoverflow.com/questions/tagged/rocketmq

nowadays, we are guiding guys to ask in stackoverflow since 4.0.0. when 4.0.0 release, you can test this problem.:-)

**Closed by vongosling** 2016-12-27 14:48 UTC
Labels: help wanted
