### ISSUE TITLE
When will be the possibility of "OVERFLOW_BADLY" happens at master?

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#351] opened 2016-09-16 06:26 UTC
I encounter a problem that master have continious "OVERFLOW_BADLY" when process a pull request from push consumer.

Now, I still cannot detect the cause and problem, from the broker's code, when overflow badly happens, the next offset will be corrected into the min offset.

But this problem continously happens. Another phenomenon is this topic consumption has gone to slave before. And this problem seems to occur from 4:00am to 5:00am , it seems that this is also related to the commit log deletions?

What will be the possible problem?

Here are some warn and error log I can see, but for some security reasons, I can't get the log out of the prod  machines, I can only provide some hints where the code flow goes to.
1. From master, at about 4:01am, I see suggest pulling slave alarm(we add this log in our broker code)
2. From slave, I can also see "suggest pulling from slave alarm continously"(we add this log in our broker code)
   3, From slave, I see MANY bug logs from storeerr.log : like 
   
   [[BUG]logic queue order maybe wrong, expectLogicOffset: xxxxx currentLogicOffset: xxxx Topic: yyyyyy QID: 0 Diff: $A_NAGETIVE_VALUE]

which should be the root cause, i guess.

---
## Client log
1. From the client, I can MANY logs from :  
   
   ```
               log.warn(
               "processQueue is dropped without process consume result. messageQueue={}, msgTreeMap={}, msgs={}",
               new Object[] { messageQueue, processQueue.getMsgTreeMap(), msgs });
       }
   ```
2. From client logs, I can also see MANY logs from: 
   
   ```
                   if (pullResult.getNextBeginOffset() < prevRequestOffset//
                           || firstMsgOffset < prevRequestOffset) {
                       log.warn(
                           "[BUG] pull message result maybe data wrong, nextBeginOffset: {} firstMsgOffset: {} prevRequestOffset: {}",//
                           pullResult.getNextBeginOffset(),//
                           firstMsgOffset,//
                           prevRequestOffset);
                   }
   ```

which for one sample like : 

```
nextBeginOffset: 1657957 firstMsgOffset: 315937 prevRequestOffset: 1657949
```

**Comment by zhouxinyu** [comment] 2016-09-17 04:42
Yes, RocketMQ will delete commit logs at 4:00am, the offset of related consume queues will be corrected if some commit logs was successfully deleted. 

In order to find the cause of your problem quickly, could you please paste the related logs(rocketmq_client.log, store.log, broker.log) here?

**Comment by Jaskey** [comment] 2016-09-18 04:57
@zhouxinyu 

I have some questions:

1. If the commit log is deleted, the consume queue will be deleted from the head, which means the min offset may be become larger but the max offset will remains, insn't it?

2. Slave and master have the same config on deleting commit logs, which will delete them on 4 am and have the same reserve time(we set it 48 hours), should I stagger them?

---------------------

Here are some logs  I collected from broker and clients, for some security reasons, I can't get the log out of my machine, I can only provide some hints where the code flow goes to.

1. From master, at about 4:01am, I see suggest pulling slave alarm(we add this log)
2. From slave, I can also see "suggest pulling from slave alarm continously"
3, From slave, I see a bug log from storeerr.log : like 

    [[BUG]logic queue order maybe wrong, expectLogicOffset: xxxxx currentLogicOffset: xxxx Topic: yyyyyy QID: 0 Diff: $A_NAGETIVE_VALUE]

which should be the root cause, i guess.


4. from the client, I can see some logs from :  
    
                    log.warn(
                    "processQueue is dropped without process consume result. messageQueue={}, msgTreeMap={}, msgs={}",
                    new Object[] { messageQueue, processQueue.getMsgTreeMap(), msgs });
            }






5. from client logs, I can also see some logs from: 

                        if (pullResult.getNextBeginOffset() < prevRequestOffset//
                                || firstMsgOffset < prevRequestOffset) {
                            log.warn(
                                "[BUG] pull message result maybe data wrong, nextBeginOffset: {} firstMsgOffset: {} prevRequestOffset: {}",//
                                pullResult.getNextBeginOffset(),//
                                firstMsgOffset,//
                                prevRequestOffset);
                        }


which for one sample is : 
    
    nextBeginOffset: 1657957 firstMsgOffset: 315937 prevRequestOffset: 1657949

**Comment by Jaskey** [comment] 2016-09-20 03:07
@zhouxinyu @vongosling any updated?

**Comment by lizhanhui** [comment] 2016-09-20 03:39
To figure out your issue, please provide as much info as possible.  The following info would be helpful to have.

1.  Version of RocketMQ used;
1.  Replication mode: async_master or sync_master;
1.  If async, figure out how much bytes slave lagged behind the master from log.

From what you provided, I can only guess your issue was caused by replication latency. More info is required to confirm.

**Comment by Jaskey** [comment] 2016-09-20 03:46
@lizhanhui 

1. 3.2.6
2. SYNC_MASTER + ASYNC_FLUSH , 2 SLAVE+ASYNC_FLUSH

**Comment by Jaskey** [comment] 2016-10-09 03:33
@vongosling 

problem is detected.

The Topic is deleted before , but the consume queue files exists in slave. If we reuse the topic after master clean its' consume queue,  master will have smaller consume queue files with slave

@vongosling , slave will possibly has unconsistent consume queue with master when recreating deleted topic , is this a bug?

Version: 3.2.6

**Comment by lizhanhui** [comment] 2016-10-14 06:50
@Jaskey  Checkout this PR: https://github.com/alibaba/RocketMQ/pull/378

Should fix your issue.

**Comment by vongosling** [comment] 2016-12-27 14:50
i close this issue  if you have any question, please ask stackoverflow. http://stackoverflow.com/questions/tagged/rocketmq

nowadays, we are guiding guys to ask in stackoverflow since 4.0.0. when 4.0.0 release, you can test this problem.:-)

**Closed by vongosling** 2016-12-27 14:50 UTC
Labels: bug, help wanted
