### ISSUE TITLE
Severe gc problem when consuming heavily-accumulated message

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#340] opened 2016-08-29 09:45 UTC
`SelectMapedBufferResult` has an overide `finalize` method which is intended to release the mapedFile.

```
    @Override
    protected void finalize() {
        if (this.mapedFile != null) {
            this.release();
        }
    }

```

In case of **40 millions** messages accummalted at one topic, and then start to consume them fastly. 

A serious gc problem has been detected, gc cost has been up to 2.7secs.

http://gceasy.io/diamondgc-report.jsp?p=c2hhcmVkLzIwMTYvMDgvMjYvLS1nMV8yMF80MDB3X20ubG9nLS05LTQ0LTE4

After I remove the finalize method, problem has been resolved :http://gceasy.io/my-gc-report.jsp?p=c2hhcmVkLzIwMTYvMDgvMjkvLS1tYXN0ZXJfbm9fZmluYWxpemUubG9nLS05LTE0LTU4

Questions:
1.  Why override to release mapfile again in `finalize` method, since the release method has been explicitly called after using `SelectMapedBufferResult`
2.  Will just removing this overided method cause some other problems?

**Comment by gaoyf** [comment] 2016-08-31 02:02
```
public synchronized void release()
```
The `release` method is synchronized. That means the GC thread will be blocked when it calls `finalize` method if `release` method is called by any thread.
So the problem may be `release` method is too slow?

**Comment by Jaskey** [comment] 2016-08-31 08:30
@gaoyf , no , it should not be. The problem is a lot of Finalizer instance and SelectMapedBufferResult instance can not be gced because of overiding `finalize` method, they are even not calling release method since `if (this.mapedFile != null) {` is not true. I have watch these instance grow fatsly from jmap dump file.

The gc problem is issue here: https://plumbr.eu/blog/garbage-collection/debugging-to-understand-finalizer

I am not sure why should overide finalize to release mmap file, since it has been release every time using `SelectMapedBufferResult ` from the callee.

**Comment by Jaskey** [comment] 2016-09-08 03:50
@vongosling any update on this issue?

**Comment by vongosling** [comment] 2016-09-08 06:58
Got it, we will check it again

**Comment by zhouxinyu** [comment] 2016-09-08 07:02
we will check it again

**Comment by Jaskey** [comment] 2016-09-12 09:41
@vongosling , at the first glance, rocket mq developer has been release the selectMappedBuffer explicitly every time ater they use them.

So in my option , the finalize method is not needed, please correct my if I am wrong, it is just for double insurancem, especially when new developer forgets to reelase it by hand, finalize method will guard it again. 

Is there any risk now I just simply remove this overirded method?

**Comment by zhouxinyu** [comment] 2016-09-12 13:01
@Jaskey , 
1. the two gc log files seem to the same ? 
2. and we don't test rocketmq with G1, Could you test this case with CMS collector?
3. Remove  the finalize method is risky, you should do enough tests to ensure it.

**Comment by Jaskey** [comment] 2016-09-12 13:57
@zhouxinyu 

1. sorry for the wrong report, please refer to the updated comments.
2. CMS will have the same problem, you could easily reproduce this problem by accumulating 400 million messages on one topic
3. what will be the risk? When designing that, what is the purpose to overide the finalize method, since it is always not a good practise to overide finalzie method.

**Comment by zhouxinyu** [comment] 2016-09-12 15:44
@Jaskey 
Got it.
1. I will reproduce your problem soon after, but it takes time. Actually I'm busy optimizing the rocketmq-store module, this problem will be solved in my new version, I promise.

2. As you see, The MappedFile won't be released if someone forgets to release  relevant SelectMapedBufferResults. If you really want to remove the finalize method, don't forget do enough tests.

3. About the purpose, I think it's owing to some historical reasons....

**Comment by vongosling** [comment] 2016-12-27 14:49
i close this issue  if you have any question, please ask stackoverflow. http://stackoverflow.com/questions/tagged/rocketmq

nowadays, we are guiding guys to ask in stackoverflow since 4.0.0. when 4.0.0 release, you can test this problem.:-)

**Closed by vongosling** 2016-12-27 14:49 UTC
Labels: bug, enhancement
