### ISSUE TITLE
Will slave always have the same consume queue/commit log with master eventually?

### ISSUE THREAD

**Issue by Jaskey** [alibaba/RocketMQ#359] opened 2016-09-21 13:36 UTC
I have encountered some problems , but before I issue them I want to make clear with something(I use SYNC_MASTER with two slaves)
1. When messages comes to master, at least this message will be sync to one slave, so the message will at least store in two machines. If my slaves has bad disk problem, will my master still consider the slave have the store the message safely and return success to my produer?
2. If everything goes well, do slaves have excatly the same commit log and consume queue file with master? Which means the commit log are exactly the same and the consume queue will excatly have the same min/max offset.
3. If some process problem occurs to my slave like the machine dies, and comes up after 2 hours, can commit log and consume queue sync with master again?
4. If some disk problem occurs to slaves, say disk is full, and after 1 hour, I release some space and the space becomes available, will the slave have the same consume queue and commit logs with master?

Please explain my above doubts, thank you!

**Comment by lizhanhui** [comment] 2016-09-21 15:22
Why not read the source code directly with these questions in mind?

**Comment by Jaskey** [comment] 2016-09-22 02:49
@lizhanhui we read through the source code and try many tests, but find some problem.
 
Before we find out the cause, we need to double confirm my doubts, since from our tests, above doubts does not  true(which seems to be a bug?)

**Comment by Jaskey** [comment] 2016-09-23 02:50
Version: 3.2.6

Here is a test result, one sync master, two slaves, we emulate that slave1 have disk full. 

And continously send message to one topic and consume it, (also, we set the acceememory ratio very small, so that the master will easily suggest pulling from slave)

Eventually, we get the topic offset and happens to see some problems, which seems to be a bug.

![image](https://cloud.githubusercontent.com/assets/5210351/18772445/8b0c3ca8-8179-11e6-9741-f50ea29b82df.png)

As the offset shows, although slave2 is healthy, it does not have exctaly the same consume queue offset with master!

Let say, 

1. queue 6, slave 2 has the same amount off message with master, but it's offset is stagger to the left(slave2_minoffset< master_minoffset , slave2_maxoffset < master_maxoffset, but slave2_maxoffset-slave1_maxoffset = master_maxoffset-maser_minoffset). 

2. Still queue 6, slave 1 has the same problem except that the max-min is not the same.

3. Shutdown slave2, and delete all it's consume queue files, restart, the consume is recover the same as master!!
 
4 . Most queue of slave1 has the same min offset but smaller max offset, which should be casue by disk full. But when we examine the max commit log offset, three brokers are the same, which means commit log is  write succfully to the slave, the consume queue is not.


-----------
Does it mean that the consume queue will be run into some inconsisten case that not sync with master even its commit log are the same or this is not granteer by rockectmq.

Can any body help to explain this?

@vongosling

**Comment by gaoyf** [comment] 2016-09-23 09:04
Did you delete the topic before? Or did you delete consume queue files in slave2 before?
I encountered this situation before, but is not exactly same with yours.
If you delete the topic, the corresponding consume queue files in the master will be deleted too, but consume queue files still in the slave.  
So if you reuse this topic, the consume queue files in the master may be has smaller offset than the slave.
As far as I know it should has nothing to do with the way of consuming.

**Comment by Jaskey** [comment] 2016-09-23 10:00
@gaoyf 

1.Do you mean slave will have smaller min offset but have the same max offset. if so this will not do with consuming

2. But from my screen shots, slaves offset have staggered,  which means it if master suggest pull from slave, it will possibly conusme the wrong message or suffering from offset illegal, doesn't it, please correct me if i am wrong.

**Comment by gaoyf** [comment] 2016-09-23 10:10
If slave has the smaller minoffset than master, the maxoffset will be smaller than the master. Because the count of message synchronizing from master is same to slave.  
My situation is that slave keeps the original consume queue, so the minoffset and maxoffset is bigger than the masters.

**Comment by gaoyf** [comment] 2016-09-23 10:57
I cannot explain your situation because I don‘t know your operation in details.  
You can analyse your broker.log, store.log & storeerror.log for clues.  
The slave uses the same code with master for building commit log & consume queue file.  
So you maybe need read the source code for find the cause, [FYI](http://blog.csdn.net/a417930422/article/details/52585204) .

**Comment by Jaskey** [comment] 2016-09-26 02:38
> My situation is that slave keeps the original consume queue, so the minoffset and maxoffset is bigger than the masters.

I guess I have the same problem!! Slaves' min offset is larger than master's max offset, when master suggest pulling from slave, slave will think the offset is too small and correct it to slave's min offset to point to master, and master will now think the offset is overflow badly, and correct it to 0(because the min offset is 0 for my topic), then continue to consume from slave from 0, which offset should be wrong since the 0 offset(as well as some small one that before deteting topic) is abandoned .


Isn't this a bug? Does new version fix this?

**Comment by Jaskey** [comment] 2016-10-09 12:39
@gaoyf 

In case of we have to move some topic from cluster A to cluster B when cluster A got some problem say cluster A has some network problem.

When cluster A recover, we will delete the A's topic in cluster B, so the slave will suffering from consume queue inconsistency with master, which is a huge problem when consuming from slave(wrong message consuming or fail to consume message).

I will consider this is a huge bug for rocketMQ, when will this bug be fixed? @vongosling 

Now, it seems that I have to mually delete the consume queue on slave and restart.

Is there any way to make them consistent? I notice there is a admin interface called: `cleanExpiredConsumerQueue` , but it only remove the queue from the map in memory which does not call cq.destroy(), is this work for this case.

**Comment by lizhanhui** [comment] 2016-10-14 04:01
Confirm this is a bug: Slave broker should compare and delete consume queues when topics have been deleted on master broker.

**Comment by vongosling** [comment] 2016-12-27 14:49
i close this issue  if you have any question, please ask stackoverflow. http://stackoverflow.com/questions/tagged/rocketmq

nowadays, we are guiding guys to ask in stackoverflow since 4.0.0. when 4.0.0 release, you can test this problem.:-)

**Closed by vongosling** 2016-12-27 14:49 UTC
Labels: help wanted
