### ISSUE TITLE
[Urgent] Why RocketMQ will not recover automatically when if disk become normal ? 

### ISSUE THREAD

**Issue by mspavan052** [alibaba/RocketMQ#331] opened 2016-08-16 07:00 UTC
Hi, 

```
   We are using the RocketMQ for out application and faced following problem.  
```

If the disk usage is more than the configured range 'diskMaxUsedSpaceRatio' (Configured 75%) then RocketMQ is rejecting the message sent from the producer saying the DISK is full. But after the disk become normal i.e., less than 50% also the Broker is not recovering (Waited for more 2 hr). 

```
 After going through the RocketMQ 3.4.6 version found following issue in code 
```

1) In ConsumeQueue.java, as shown below if the disk has become full & there are some messages in the DispatchRequest to write into the ConsumeQueue file, then the 'canWrite = this.defaultMessageStore.getRunningFlags().isWriteable();' flag will be become false and mark as logicalError 

 public void putMessagePostionInfoWrapper(long offset, int size, long tagsCode, long storeTimestamp,
            long logicOffset) {
        final int MaxRetries = 30;
        boolean canWrite = this.defaultMessageStore.getRunningFlags().isWriteable();
        for (int i = 0; i < MaxRetries && canWrite; i++) {
            boolean result = this.putMessagePostionInfo(offset, size, tagsCode, logicOffset);
            if (result) {
                this.defaultMessageStore.getStoreCheckpoint().setLogicsMsgTimestamp(storeTimestamp);
                return;
            }
            else {
                log.warn("[BUG]put commit log postion info to " + topic + ":" + queueId + " " + offset
                        + " failed, retry " + i + " times");

```
            try {
                Thread.sleep(1000);
            }
            catch (InterruptedException e) {
                log.warn("", e);
            }
        }
    }

    log.error("[BUG]consume queue can not write, {} {}", this.topic, this.queueId);
    this.defaultMessageStore.getRunningFlags().makeLogicsQueueError();
}
```

2) In RunningFlags.java 
          If WriteLogicsQueueErrorBit is set then isWriteable() will return false and no method will set it back to normal even after the diskBecome normal. ( getAndMakeDiskOK - will mark only the diskfull flag)

 In this scenario the RocketMQ will never recover even though the disk become normal. 

Question: 
                 Is this intended behavior or bug ?  If its intended behavior, can you please give explanation and how to handle by the application ? 

With Regards,
Pavan

**Comment by lizhanhui** [comment] 2016-08-16 10:20
Hi Pavan, 
You missed to check the `CleanCommitLogService` which runs periodically  and would mark the store writable once there are enough space.  In particular, see line #1168 of DefaultMessageStore.java 

The reason why your broker is still not writable after 2 hours of "the disk become normal", I guess, lies in the approach how you made the disk become normal. Did the clean service delete some commit log files after they became obsolete? Or, you manually delete some commit log files which OS still treats them as held.

**Comment by mspavan052** [comment] 2016-08-16 12:20
Thanks for your quick reply, 

1) In particular, see line #1168 of DefaultMessageStore.java 
    --> I checked this, but it will call getAndMakeDiskOK() which makes only diskFULLBit but the WriteLogicsQueueErrorBit will not be updated.  So it will never become writable even the disk become normal. 

       Exact scenario
           a) Produce 10000 messages in async mode
           b) Disk become more than 75% when commited 80000 messages, so diskFullBit is set to true
           c) Broker started rejecting the messages
           d) In backgrond the DispatchService is trying to write to the consumeQueue for 80000 messages which are already commited.  This time in putMessagePostionInfoWrapper(), (ConsumeQueue # 339) it will find 'canWrite' is false as diskFullBit is set before. So it will mark the logicQueue Error.  
                 this.defaultMessageStore.getRunningFlags().makeLogicsQueueError();
           e) Once this logQueueErrorBit is set, there is no way it will recover even though the disk become normal as part of commitlog file deletion. 

So here my question, 
         Why we need to make logicQuickError ? why this bit will not be changed any time unless restarting of the broker.


2) Verified with both commitlog file deletion by Broker itself and manual deletion of file also. Both cases same problem is coming.

**Comment by lizhanhui** [comment] 2016-08-17 02:18
"Why we need to make logicQuickError ?" In the current implementation, marking the consumeQueue logical error is necessary as there are one or more messages written to commit log file but appending logical consume records are failed, aka, consume queues are not synchronized with commit log. The store is in a state of discrepancy. 

"why this bit will not be changed any time unless restarting of the broker."  This is because recoverConsumeQueue method, line #1008 of DefaultMessageStore.java, is only executed at broker restarting. 

Admittedly, the current implementation leaves much space to improve. For example, when disk is insufficient, just mark the store as full, allowing consume queues to write as normal as consume queues are generally small comparing to the reserved space; Or initiate recoverConsumeQueue method when disk becomes normal, which hopefully may recover the logic discrepancy caused by previous disk-full scenario.

**Comment by vongosling** [comment] 2016-08-17 02:37
There are two question before we go deep into this problem. the first one is 80000 messages led to your disk 75% usage, what size your one message, and can you paste your machine configuration? the second one, can you tell me your use case for our RocketMQ,especially industry description?  

Also ,we are planning to refactor again the message store logic for some low latency scenario. welcome to your advice

**Comment by vongosling** [comment] 2016-12-27 14:47
i close this issue  if you have any question, please ask stackoverflow. http://stackoverflow.com/questions/tagged/rocketmq

nowadays, we are guiding guys to ask in stackoverflow since 4.0.0

**Closed by vongosling** 2016-12-27 14:47 UTC
Labels: help wanted
